services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app/backend
      - ./img:/usr/src/app/img
      - /usr/src/app/backend/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: